title: Mohamed Albirair
# logo: /
description: Implementation science researcher, R programmer of quantitative analysis and data visualization, mathematical modeler, and research methods teacher.
show_downloads: true
theme: jekyll-theme-minimal
