title: Mohamed Albirair
logo: ./assets/img/portfolio/Mohamed-Albirair_050522_001-2.jpg
description: Implementation science researcher, R programmer of quantitative analysis and data visualization, mathematical modeler, and research methods teacher.
show_downloads: true
theme: jekyll-theme-minimal
